# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5decf1f035b4a7bd8f85388654206dffeb0ef5ca8cfa4486d09636dc96a32c15eca84d93598d6d8ff06cda0f2fac03c48359b810691ea569f201019de9d5648a

test:
  secret_key_base: 4639b1d6236a637e8a620a78e509df95a7c164f52db102b6e98cceea18d7f9b290b17427846c58d3d8a25d5d0d60d5696b8a7901c5e78bd4d6be4410edd6a196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
